//MERCANTIL
export const PAGAR_MERCANTIL='PAGAR_MERCANTIL';

//PAY
export const GET_YEARS_TDC='GET_YEARS_TDC';
export const GET_MONTHS_TDC='GET_MONTHS_TDC';
export const SET_LOADING='SET_LOADING';
export const CHANGE_METHOD='CHANGE_METHOD';
export const CHANGE_COIN='CHANGE_COIN';
export const PAYMENT='PAYMENT';
export const FORM_PAYMENT='FORM_PAYMENT';